package com.bory.eventsourcingtutorial.employee.infrastructure.eventlistener

import com.bory.eventsourcingtutorial.core.infrastructure.annotations.DomainEventListener
import org.springframework.transaction.annotation.Transactional

@Transactional
@DomainEventListener
class EmployeeEventListener