GET http://localhost:8080/api/v1/clients/02e4cb64-6379-4e3d-a96e-1331bd3e0760
Accept: application/json

###

GET http://localhost:8080/api/v1/clients/snapshot/02e4cb64-6379-4e3d-a96e-1331bd3e0760
Accept: application/json